{
 "title": "Spacemesh Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "percentile",
    "query": "0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,0.95,0.99"
   },
   { "name": "sign", "query": "pos, neg" }
  ]
 },
 "panels": [
  {
   "title": "Sync Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "spacemesh_syncer_sync_state{state=\"synced\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Activation Publish On Time",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "spacemesh_activation_publish_window_seconds_count{condition=\"ontime\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "spacemesh_p2p_peers_per_protocol",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ATX Sync Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "spacemesh_syncer_sync_state{state=\"atx_synced\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Activation POET pow duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "spacemesh_activation_poet_pow_duration / 1000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Activation Post Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "spacemesh_activation_post_duration / 1000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Synced Layer min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min(spacemesh_syncer_layer)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Synced Layer max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(spacemesh_syncer_layer)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Message Latencies Hare Commit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, type, instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\", sign=\"$sign\", type=\"commit\"}[5m]))",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies hr1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\", sign=\"$sign\"}[5m]))",
     "legendFormat": "hr1-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Hare Notify",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, type, instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\", sign=\"$sign\", type=\"notify\"}[5m]))",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies pp1",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le,instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"pp1\",sign=\"$sign\"}[5m]))",
     "legendFormat": "pp1-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Hare Preround",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, type, instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\", sign=\"$sign\", type=\"preround\"}[5m]))",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Atx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " sum by(le,instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"ax1\"}[5m]))",
     "legendFormat": "Activation-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Hare Proposal",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, type, instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\", sign=\"$sign\", type=\"proposal\"}[5m]))",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Beacon",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(spacemesh_message_latency_seconds_count{protocol=\"b1\", sign=\"$sign\"}[5m])) by (le,type,instance)",
     "legendFormat": "{{type}}{{instance}}"
    }
   ]
  },
  {
   "title": "Message Latencies Hare Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, type, instance) (rate(spacemesh_message_latency_seconds_count{protocol=\"hr1\", sign=\"$sign\", type=\"status\"}[5m]))",
     "legendFormat": "{{type}}-{{instance}}"
    }
   ]
  }
 ]
}